<%--
  Copyright 2017 Google Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  \
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
--%>
<%@ page import="java.util.List" %>
<%@ page import="codeu.model.data.Conversation" %>
<%@ page import="codeu.model.data.Message" %>
<%@ page import="codeu.model.store.basic.UserStore" %>
<%@ page import="com.vdurmont.emoji.EmojiParser" %>
<%@ page import="javax.swing.*" %>
<%@ page import="javax.swing.event.DocumentEvent"%>
<%@ page import="javax.swing.event.DocumentListener"%>
<%@ page import="javax.swing.text.*"%>
<%@ page import="java.awt.image.BufferedImage"%>
<%@ page import="java.awt.*" %>

<%
Conversation conversation = (Conversation) request.getAttribute("conversation");
List<Message> messages = (List<Message>) request.getAttribute("messages");
%>

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title><%= conversation.getTitle() %></title>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="/css/main.css">
  <style>
    #chat {
      background-color: white;
      height: 350px;
      overflow-y: scroll
    }
  </style>

  <script>
    // scroll the chat div to the bottom
    function scrollChat() {
      var chatDiv = document.getElementById('chat');
      chatDiv.scrollTop = chatDiv.scrollHeight;
    };
  </script>
</head>


 <nav class="navbar navbar-default" role="navigation">
   <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="/">MURMUR</a>
   </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
       <% if(request.getSession().getAttribute("user") != null){ %>
      <li> <a>Hello <%= request.getSession().getAttribute("user") %>!</a>
     <% } else{ %>
       <a href="/login">Login</a></li>
     <% } %>
       <li><a href="/about.jsp">About</a></li>
       <% if(request.getSession().getAttribute("user") != null){ %>
       <li><a href="/activityfeed">Feed</a></li>
       <% }  %>
       <% if(request.getSession().getAttribute("user") != null){ %>
       <li><a href="/conversations">Conversations</a></li>
        <% }  %>
       <% if(request.getSession().getAttribute("user") != null){ %>
       <li><a href="/mentions" > Notifications</a></li>
        <% }  %>
       <li><a href="/user/<%=request.getSession().getAttribute("user")%>">Profile</a></li>
       <% if(request.getSession().getAttribute("user") != null){ %>
       <li><a href="/logout" > Logout</a></li>
        <% }  %>
     </ul>
   </div><!-- /.navbar-collapse -->
 </nav>
<body onload="scrollChat()">
  <div id="container">
    <h1><%= conversation.getTitle() %>
      <a href="" style="float: right">&#8635;</a></h1>
    <hr/>
    <div id="chat">
      <ul>
        <%
         String currentUser= "@" + request.getSession().getAttribute("user");
          for (Message message : messages) {
          String author = UserStore.getInstance().getUser(message.getAuthorId()).getName();
         %>
         <li><strong><a href="/user/<%=author%>"><%= author %></a></strong></li>
         <%  if(message.getContent().contains(currentUser)){ %>
              <strong><%= message.getContent() %></strong>
           <%} else{%>
            <%= message.getContent() %>
         <%
          }
      } %>
      </li>
      </ul>
    </div>
    <hr/>
    <% if (request.getSession().getAttribute("user") != null) { %>
    <form action="/chat/<%= conversation.getTitle() %>" method="POST">
        <input type="text" name="message">
        <br/>
        <button type="submit">Send</button>
    </form>
    <% } else { %>
      <p><a href="/login">Login</a> to send a message.</p>
    <% } %>
    <hr/>
  </div>

<%String guished = EmojiParser.parseToUnicode(":guished:");%>
<%String open_mouth = EmojiParser.parseToUnicode(":open_mouth:");%>
<%String grimacing = EmojiParser.parseToUnicode(":grimacing:");%>
<%String confused = EmojiParser.parseToUnicode(":confused:");%>
<%String hushed = EmojiParser.parseToUnicode(":hushed:");%>
<%String expressionless = EmojiParser.parseToUnicode(":expressionless:");%>
<%String unamused = EmojiParser.parseToUnicode(":unamused:");%>
<%String sweat_smile = EmojiParser.parseToUnicode(":sweat_smile:");%>
<%String sweat = EmojiParser.parseToUnicode(":sweat:");%>
<%String disappointed_relieved = EmojiParser.parseToUnicode(":disappointed_relieved:");%>
<%String weary = EmojiParser.parseToUnicode(":weary:");%>
<%String pensive = EmojiParser.parseToUnicode(":pensive:");%>
<%String disappointed = EmojiParser.parseToUnicode(":disappointed:");%>
<%String confounded = EmojiParser.parseToUnicode(":confounded:");%>
<%String fearful = EmojiParser.parseToUnicode(":fearful:");%>
<%String cold_sweat = EmojiParser.parseToUnicode(":cold_sweat:");%>
<%String persevere = EmojiParser.parseToUnicode(":persevere:");%>
<%String cry = EmojiParser.parseToUnicode(":cry:");%>
<%String sob = EmojiParser.parseToUnicode(":sob:");%>
<%String joy = EmojiParser.parseToUnicode(":joy:");%>
<%String astonished = EmojiParser.parseToUnicode(":astonished:");%>
<%String scream = EmojiParser.parseToUnicode(":scream:");%>
<%String neckbeard = EmojiParser.parseToUnicode(":neckbeard:");%>
<%String tired_face = EmojiParser.parseToUnicode(":tired_face:");%>
<%String angry = EmojiParser.parseToUnicode(":angry:");%>
<%String rage = EmojiParser.parseToUnicode(":rage:");%>
<%String triumph = EmojiParser.parseToUnicode(":triumph:");%>
<%String sleepy = EmojiParser.parseToUnicode(":sleepy:");%>
<%String yum = EmojiParser.parseToUnicode(":yum:");%>
<%String mask = EmojiParser.parseToUnicode(":mask:");%>
<%String sunglasses = EmojiParser.parseToUnicode(":sunglasses:");%>
<%String dizzy_face = EmojiParser.parseToUnicode(":dizzy_face:");%>
<%String imp = EmojiParser.parseToUnicode(":imp:");%>
<%String smiling_imp = EmojiParser.parseToUnicode(":smiling_imp:");%>
<%String neutral_face = EmojiParser.parseToUnicode(":neutral_face:");%>
<%String no_mouth = EmojiParser.parseToUnicode(":no_mouth:");%>
<%String innocent = EmojiParser.parseToUnicode(":innocent:");%>
<%String alien = EmojiParser.parseToUnicode(":alien:");%>
<%String yellow_heart = EmojiParser.parseToUnicode(":yellow_heart:");%>
<%String blue_heart = EmojiParser.parseToUnicode(":blue_heart:");%>
<%String purple_heart = EmojiParser.parseToUnicode(":purple_heart:");%>
<%String heart = EmojiParser.parseToUnicode(":heart:");%>
<%String green_heart = EmojiParser.parseToUnicode(":green_heart:");%>
<%String broken_heart = EmojiParser.parseToUnicode(":broken_heart:");%>
<%String heartbeat = EmojiParser.parseToUnicode(":heartbeat:");%>
<%String heartpulse = EmojiParser.parseToUnicode(":heartpulse:");%>
<%String two_hearts = EmojiParser.parseToUnicode(":two_hearts:");%>
<%String revolving_hearts = EmojiParser.parseToUnicode(":revolving_hearts:");%>
<%String cupid = EmojiParser.parseToUnicode(":cupid:");%>
<%String sparkling_heart = EmojiParser.parseToUnicode(":sparkling_heart:");%>
<%String sparkles = EmojiParser.parseToUnicode(":sparkles:");%>
<%String star = EmojiParser.parseToUnicode(":star:");%>
<%String star2 = EmojiParser.parseToUnicode(":star2:");%>
<%String dizzy = EmojiParser.parseToUnicode(":dizzy:");%>
<%String boom = EmojiParser.parseToUnicode(":boom:");%>
<%String collision = EmojiParser.parseToUnicode(":collision:");%>
<%String anger = EmojiParser.parseToUnicode(":anger:");%>
<%String exclamation = EmojiParser.parseToUnicode(":exclamation:");%>
<%String question = EmojiParser.parseToUnicode(":question:");%>
<%String grey_exclamation = EmojiParser.parseToUnicode(":grey_exclamation:");%>
<%String grey_question = EmojiParser.parseToUnicode(":grey_question:");%>
<%String zzz = EmojiParser.parseToUnicode(":zzz:");%>
<%String dash = EmojiParser.parseToUnicode(":dash:");%>
<%String sweat_drops = EmojiParser.parseToUnicode(":sweat_drops:");%>
<%String notes = EmojiParser.parseToUnicode(":notes:");%>
<%String musical_note = EmojiParser.parseToUnicode(":musical_note:");%>
<%String fire = EmojiParser.parseToUnicode(":fire:");%>
<%String hankey = EmojiParser.parseToUnicode(":hankey:");%>
<%String poop = EmojiParser.parseToUnicode(":poop:");%>
<%String shit = EmojiParser.parseToUnicode(":shit:");%>
<%String thumbsup = EmojiParser.parseToUnicode(":thumbsup:");%>
<%String thumbsdown = EmojiParser.parseToUnicode(":thumbsdown:");%>
<%String ok_hand = EmojiParser.parseToUnicode(":ok_hand:");%>
<%String punch = EmojiParser.parseToUnicode(":punch:");%>
<%String facepunch = EmojiParser.parseToUnicode(":facepunch:");%>
<%String fist = EmojiParser.parseToUnicode(":fist:");%>
<%String v = EmojiParser.parseToUnicode(":v:");%>
<%String wave = EmojiParser.parseToUnicode(":wave:");%>
<%String hand = EmojiParser.parseToUnicode(":hand:");%>
<%String raised_hand = EmojiParser.parseToUnicode(":raised_hand:");%>
<%String open_hands = EmojiParser.parseToUnicode(":open_hands:");%>
<%String point_up = EmojiParser.parseToUnicode(":point_up:");%>
<%String point_down = EmojiParser.parseToUnicode(":point_down:");%>
<%String point_left = EmojiParser.parseToUnicode(":point_left:");%>
<%String point_right = EmojiParser.parseToUnicode(":point_right:");%>
<%String raised_hands = EmojiParser.parseToUnicode(":raised_hands:");%>
<%String pray = EmojiParser.parseToUnicode(":pray:");%>
<%String point_up_2 = EmojiParser.parseToUnicode(":point_up_2:");%>
<%String clap = EmojiParser.parseToUnicode(":clap:");%>
<%String muscle = EmojiParser.parseToUnicode(":muscle:");%>
<%String metal = EmojiParser.parseToUnicode(":metal:");%>
<%String fu = EmojiParser.parseToUnicode(":fu:");%>
<%String runner = EmojiParser.parseToUnicode(":runner:");%>
<%String running = EmojiParser.parseToUnicode(":running:");%>
<%String couple = EmojiParser.parseToUnicode(":couple:");%>
<%String family = EmojiParser.parseToUnicode(":family:");%>
<%String two_men_holding_hands = EmojiParser.parseToUnicode(":two_men_holding_hands:");%>
<%String two_women_holding_hands = EmojiParser.parseToUnicode(":two_women_holding_hands:");%>
<%String dancer = EmojiParser.parseToUnicode(":dancer:");%>
<%String dancers = EmojiParser.parseToUnicode(":dancers:");%>
<%String ok_woman = EmojiParser.parseToUnicode(":ok_woman:");%>
<%String no_good = EmojiParser.parseToUnicode(":no_good:");%>
<%String information_desk_person = EmojiParser.parseToUnicode(":information_desk_person:");%>
<%String raising_hand = EmojiParser.parseToUnicode(":raising_hand:");%>
<%String bride_with_veil = EmojiParser.parseToUnicode(":bride_with_veil:");%>
<%String person_with_pouting_face = EmojiParser.parseToUnicode(":person_with_pouting_face:");%>
<%String person_frowning = EmojiParser.parseToUnicode(":person_frowning:");%>
<%String bow = EmojiParser.parseToUnicode(":bow:");%>
<%String couplekiss = EmojiParser.parseToUnicode(":couplekiss:");%>
<%String couple_with_heart = EmojiParser.parseToUnicode(":couple_with_heart:");%>
<%String massage = EmojiParser.parseToUnicode(":massage:");%>
<%String haircut = EmojiParser.parseToUnicode(":haircut:");%>
<%String nail_care = EmojiParser.parseToUnicode(":nail_care:");%>
<%String boy = EmojiParser.parseToUnicode(":boy:");%>
<%String girl = EmojiParser.parseToUnicode(":girl:");%>
<%String woman = EmojiParser.parseToUnicode(":woman:");%>
<%String man = EmojiParser.parseToUnicode(":man:");%>
<%String baby = EmojiParser.parseToUnicode(":baby:");%>
<%String older_woman = EmojiParser.parseToUnicode(":older_woman:");%>
<%String older_man = EmojiParser.parseToUnicode(":older_man:");%>
<%String person_with_blond_hair = EmojiParser.parseToUnicode(":person_with_blond_hair:");%>
<%String man_with_gua_pi_mao = EmojiParser.parseToUnicode(":man_with_gua_pi_mao:");%>
<%String man_with_turban = EmojiParser.parseToUnicode(":man_with_turban:");%>
<%String construction_worker = EmojiParser.parseToUnicode(":construction_worker:");%>
<%String cop = EmojiParser.parseToUnicode(":cop:");%>
<%String angel = EmojiParser.parseToUnicode(":angel:");%>
<%String princess = EmojiParser.parseToUnicode(":princess:");%>
<%String smiley_cat = EmojiParser.parseToUnicode(":smiley_cat:");%>
<%String smile_cat = EmojiParser.parseToUnicode(":smile_cat:");%>
<%String heart_eyes_cat = EmojiParser.parseToUnicode(":heart_eyes_cat:");%>
<%String kissing_cat = EmojiParser.parseToUnicode(":kissing_cat:");%>
<%String smirk_cat = EmojiParser.parseToUnicode(":smirk_cat:");%>
<%String scream_cat = EmojiParser.parseToUnicode(":scream_cat:");%>
<%String crying_cat_face = EmojiParser.parseToUnicode(":crying_cat_face:");%>
<%String joy_cat = EmojiParser.parseToUnicode(":joy_cat:");%>
<%String pouting_cat = EmojiParser.parseToUnicode(":pouting_cat:");%>
<%String japanese_ogre = EmojiParser.parseToUnicode(":japanese_ogre:");%>
<%String japanese_goblin = EmojiParser.parseToUnicode(":japanese_goblin:");%>
<%String see_no_evil = EmojiParser.parseToUnicode(":see_no_evil:");%>
<%String hear_no_evil = EmojiParser.parseToUnicode(":hear_no_evil:");%>
<%String speak_no_evil = EmojiParser.parseToUnicode(":speak_no_evil:");%>
<%String guardsman = EmojiParser.parseToUnicode(":guardsman:");%>
<%String skull = EmojiParser.parseToUnicode(":skull:");%>
<%String feet = EmojiParser.parseToUnicode(":feet:");%>
<%String lips = EmojiParser.parseToUnicode(":lips:");%>
<%String kiss = EmojiParser.parseToUnicode(":kiss:");%>
<%String droplet = EmojiParser.parseToUnicode(":droplet:");%>
<%String ear = EmojiParser.parseToUnicode(":ear:");%>
<%String eyes = EmojiParser.parseToUnicode(":eyes:");%>
<%String nose = EmojiParser.parseToUnicode(":nose:");%>
<%String tongue = EmojiParser.parseToUnicode(":tongue:");%>
<%String love_letter = EmojiParser.parseToUnicode(":love_letter:");%>
<%String bust_in_silhouette = EmojiParser.parseToUnicode(":bust_in_silhouette:");%>
<%String busts_in_silhouette = EmojiParser.parseToUnicode(":busts_in_silhouette:");%>
<%String speech_balloon = EmojiParser.parseToUnicode(":speech_balloon:");%>
<%String thought_balloon = EmojiParser.parseToUnicode(":thought_balloon:");%>
<%String feelsgood = EmojiParser.parseToUnicode(":feelsgood:");%>
<%String finnadie = EmojiParser.parseToUnicode(":finnadie:");%>
<%String goberserk = EmojiParser.parseToUnicode(":goberserk:");%>
<%String godmode = EmojiParser.parseToUnicode(":godmode:");%>
<%String hurtrealbad = EmojiParser.parseToUnicode(":hurtrealbad:");%>
<%String rage1 = EmojiParser.parseToUnicode(":rage1:");%>
<%String rage2 = EmojiParser.parseToUnicode(":rage2:");%>
<%String rage3 = EmojiParser.parseToUnicode(":rage3:");%>
<%String rage4 = EmojiParser.parseToUnicode(":rage4:");%>
<%String suspect = EmojiParser.parseToUnicode(":suspect:");%>
<%String trollface = EmojiParser.parseToUnicode(":trollface:");%>
<%String sunny = EmojiParser.parseToUnicode(":sunny:");%>
<%String umbrella = EmojiParser.parseToUnicode(":umbrella:");%>
<%String cloud = EmojiParser.parseToUnicode(":cloud:");%>
<%String snowflake = EmojiParser.parseToUnicode(":snowflake:");%>
<%String snowman = EmojiParser.parseToUnicode(":snowman:");%>
<%String zap = EmojiParser.parseToUnicode(":zap:");%>
<%String cyclone = EmojiParser.parseToUnicode(":cyclone:");%>
<%String foggy = EmojiParser.parseToUnicode(":foggy:");%>
<%String ocean = EmojiParser.parseToUnicode(":ocean:");%>
<%String cat = EmojiParser.parseToUnicode(":cat:");%>
<%String dog = EmojiParser.parseToUnicode(":dog:");%>
<%String mouse = EmojiParser.parseToUnicode(":mouse:");%>
<%String hamster = EmojiParser.parseToUnicode(":hamster:");%>
<%String rabbit = EmojiParser.parseToUnicode(":rabbit:");%>
<%String wolf = EmojiParser.parseToUnicode(":wolf:");%>
<%String frog = EmojiParser.parseToUnicode(":frog:");%>
<%String tiger = EmojiParser.parseToUnicode(":tiger:");%>
<%String koala = EmojiParser.parseToUnicode(":koala:");%>
<%String bear = EmojiParser.parseToUnicode(":bear:");%>
<%String pig = EmojiParser.parseToUnicode(":pig:");%>
<%String pig_nose = EmojiParser.parseToUnicode(":pig_nose:");%>
<%String cow = EmojiParser.parseToUnicode(":cow:");%>
<%String boar = EmojiParser.parseToUnicode(":boar:");%>
<%String monkey_face = EmojiParser.parseToUnicode(":monkey_face:");%>
<%String monkey = EmojiParser.parseToUnicode(":monkey:");%>
<%String horse = EmojiParser.parseToUnicode(":horse:");%>
<%String racehorse = EmojiParser.parseToUnicode(":racehorse:");%>
<%String camel = EmojiParser.parseToUnicode(":camel:");%>
<%String sheep = EmojiParser.parseToUnicode(":sheep:");%>
<%String elephant = EmojiParser.parseToUnicode(":elephant:");%>
<%String panda_face = EmojiParser.parseToUnicode(":panda_face:");%>
<%String snake = EmojiParser.parseToUnicode(":snake:");%>
<%String bird = EmojiParser.parseToUnicode(":bird:");%>
<%String baby_chick = EmojiParser.parseToUnicode(":baby_chick:");%>
<%String hatched_chick = EmojiParser.parseToUnicode(":hatched_chick:");%>
<%String hatching_chick = EmojiParser.parseToUnicode(":hatching_chick:");%>
<%String chicken = EmojiParser.parseToUnicode(":chicken:");%>
<%String penguin = EmojiParser.parseToUnicode(":penguin:");%>
<%String turtle = EmojiParser.parseToUnicode(":turtle:");%>
<%String bug = EmojiParser.parseToUnicode(":bug:");%>
<%String honeybee = EmojiParser.parseToUnicode(":honeybee:");%>
<%String ant = EmojiParser.parseToUnicode(":ant:");%>
<%String beetle = EmojiParser.parseToUnicode(":beetle:");%>
<%String snail = EmojiParser.parseToUnicode(":snail:");%>
<%String octopus = EmojiParser.parseToUnicode(":octopus:");%>
<%String tropical_fish = EmojiParser.parseToUnicode(":tropical_fish:");%>
<%String fish = EmojiParser.parseToUnicode(":fish:");%>
<%String whale = EmojiParser.parseToUnicode(":whale:");%>
<%String whale2 = EmojiParser.parseToUnicode(":whale2:");%>
<%String dolphin = EmojiParser.parseToUnicode(":dolphin:");%>
<%String cow2 = EmojiParser.parseToUnicode(":cow2:");%>
<%String ram = EmojiParser.parseToUnicode(":ram:");%>
<%String rat = EmojiParser.parseToUnicode(":rat:");%>
<%String water_buffalo = EmojiParser.parseToUnicode(":water_buffalo:");%>
<%String tiger2 = EmojiParser.parseToUnicode(":tiger2:");%>
<%String rabbit2 = EmojiParser.parseToUnicode(":rabbit2:");%>
<%String dragon = EmojiParser.parseToUnicode(":dragon:");%>
<%String goat = EmojiParser.parseToUnicode(":goat:");%>
<%String rooster = EmojiParser.parseToUnicode(":rooster:");%>
<%String dog2 = EmojiParser.parseToUnicode(":dog2:");%>
<%String pig2 = EmojiParser.parseToUnicode(":pig2:");%>
<%String mouse2 = EmojiParser.parseToUnicode(":mouse2:");%>
<%String ox = EmojiParser.parseToUnicode(":ox:");%>
<%String dragon_face = EmojiParser.parseToUnicode(":dragon_face:");%>
<%String blowfish = EmojiParser.parseToUnicode(":blowfish:");%>
<%String crocodile = EmojiParser.parseToUnicode(":crocodile:");%>
<%String dromedary_camel = EmojiParser.parseToUnicode(":dromedary_camel:");%>
<%String leopard = EmojiParser.parseToUnicode(":leopard:");%>
<%String cat2 = EmojiParser.parseToUnicode(":cat2:");%>
<%String poodle = EmojiParser.parseToUnicode(":poodle:");%>
<%String paw_prints = EmojiParser.parseToUnicode(":paw_prints:");%>
<%String bouquet = EmojiParser.parseToUnicode(":bouquet:");%>
<%String cherry_blossom = EmojiParser.parseToUnicode(":cherry_blossom:");%>
<%String tulip = EmojiParser.parseToUnicode(":tulip:");%>
<%String four_leaf_clover = EmojiParser.parseToUnicode(":four_leaf_clover:");%>
<%String rose = EmojiParser.parseToUnicode(":rose:");%>
<%String sunflower = EmojiParser.parseToUnicode(":sunflower:");%>
<%String hibiscus = EmojiParser.parseToUnicode(":hibiscus:");%>
<%String maple_leaf = EmojiParser.parseToUnicode(":maple_leaf:");%>
<%String leaves = EmojiParser.parseToUnicode(":leaves:");%>
<%String fallen_leaf = EmojiParser.parseToUnicode(":fallen_leaf:");%>
<%String herb = EmojiParser.parseToUnicode(":herb:");%>
<%String mushroom = EmojiParser.parseToUnicode(":mushroom:");%>
<%String cactus = EmojiParser.parseToUnicode(":cactus:");%>
<%String palm_tree = EmojiParser.parseToUnicode(":palm_tree:");%>
<%String evergreen_tree = EmojiParser.parseToUnicode(":evergreen_tree:");%>
<%String deciduous_tree = EmojiParser.parseToUnicode(":deciduous_tree:");%>
<%String chestnut = EmojiParser.parseToUnicode(":chestnut:");%>
<%String seedling = EmojiParser.parseToUnicode(":seedling:");%>
<%String blossom = EmojiParser.parseToUnicode(":blossom:");%>
<%String ear_of_rice = EmojiParser.parseToUnicode(":ear_of_rice:");%>
<%String shell = EmojiParser.parseToUnicode(":shell:");%>
<%String globe_with_meridians = EmojiParser.parseToUnicode(":globe_with_meridians:");%>
<%String sun_with_face = EmojiParser.parseToUnicode(":sun_with_face:");%>
<%String full_moon_with_face = EmojiParser.parseToUnicode(":full_moon_with_face:");%>
<%String new_moon_with_face = EmojiParser.parseToUnicode(":new_moon_with_face:");%>
<%String new_moon = EmojiParser.parseToUnicode(":new_moon:");%>
<%String waxing_crescent_moon = EmojiParser.parseToUnicode(":waxing_crescent_moon:");%>
<%String first_quarter_moon = EmojiParser.parseToUnicode(":first_quarter_moon:");%>
<%String waxing_gibbous_moon = EmojiParser.parseToUnicode(":waxing_gibbous_moon:");%>
<%String full_moon = EmojiParser.parseToUnicode(":full_moon:");%>
<%String waning_gibbous_moon = EmojiParser.parseToUnicode(":waning_gibbous_moon:");%>
<%String last_quarter_moon = EmojiParser.parseToUnicode(":last_quarter_moon:");%>
<%String waning_crescent_moon = EmojiParser.parseToUnicode(":waning_crescent_moon:");%>
<%String last_quarter_moon_with_face = EmojiParser.parseToUnicode(":last_quarter_moon_with_face:");%>
<%String first_quarter_moon_with_face = EmojiParser.parseToUnicode(":first_quarter_moon_with_face:");%>
<%String crescent_moon = EmojiParser.parseToUnicode(":crescent_moon:");%>
<%String earth_africa = EmojiParser.parseToUnicode(":earth_africa:");%>
<%String earth_americas = EmojiParser.parseToUnicode(":earth_americas:");%>
<%String earth_asia = EmojiParser.parseToUnicode(":earth_asia:");%>
<%String volcano = EmojiParser.parseToUnicode(":volcano:");%>
<%String milky_way = EmojiParser.parseToUnicode(":milky_way:");%>
<%String partly_sunny = EmojiParser.parseToUnicode(":partly_sunny:");%>
<%String octocat = EmojiParser.parseToUnicode(":octocat:");%>
<%String squirrel = EmojiParser.parseToUnicode(":squirrel:");%>
<%String bamboo = EmojiParser.parseToUnicode(":bamboo:");%>
<%String gift_heart = EmojiParser.parseToUnicode(":gift_heart:");%>
<%String dolls = EmojiParser.parseToUnicode(":dolls:");%>
<%String school_satchel = EmojiParser.parseToUnicode(":school_satchel:");%>
<%String mortar_board = EmojiParser.parseToUnicode(":mortar_board:");%>
<%String flags = EmojiParser.parseToUnicode(":flags:");%>
<%String fireworks = EmojiParser.parseToUnicode(":fireworks:");%>
<%String sparkler = EmojiParser.parseToUnicode(":sparkler:");%>
<%String wind_chime = EmojiParser.parseToUnicode(":wind_chime:");%>
<%String rice_scene = EmojiParser.parseToUnicode(":rice_scene:");%>
<%String jack_o_lantern = EmojiParser.parseToUnicode(":jack_o_lantern:");%>
<%String ghost = EmojiParser.parseToUnicode(":ghost:");%>
<%String santa = EmojiParser.parseToUnicode(":santa:");%>
<%String christmas_tree = EmojiParser.parseToUnicode(":christmas_tree:");%>
<%String gift = EmojiParser.parseToUnicode(":gift:");%>
<%String bell = EmojiParser.parseToUnicode(":bell:");%>
<%String no_bell = EmojiParser.parseToUnicode(":no_bell:");%>
<%String tanabata_tree = EmojiParser.parseToUnicode(":tanabata_tree:");%>
<%String tada = EmojiParser.parseToUnicode(":tada:");%>
<%String confetti_ball = EmojiParser.parseToUnicode(":confetti_ball:");%>
<%String balloon = EmojiParser.parseToUnicode(":balloon:");%>
<%String crystal_ball = EmojiParser.parseToUnicode(":crystal_ball:");%>
<%String cd = EmojiParser.parseToUnicode(":cd:");%>
<%String dvd = EmojiParser.parseToUnicode(":dvd:");%>
<%String floppy_disk = EmojiParser.parseToUnicode(":floppy_disk:");%>
<%String camera = EmojiParser.parseToUnicode(":camera:");%>
<%String video_camera = EmojiParser.parseToUnicode(":video_camera:");%>
<%String movie_camera = EmojiParser.parseToUnicode(":movie_camera:");%>
<%String computer = EmojiParser.parseToUnicode(":computer:");%>
<%String tv = EmojiParser.parseToUnicode(":tv:");%>
<%String iphone = EmojiParser.parseToUnicode(":iphone:");%>
<%String phone = EmojiParser.parseToUnicode(":phone:");%>
<%String telephone = EmojiParser.parseToUnicode(":telephone:");%>
<%String telephone_receiver = EmojiParser.parseToUnicode(":telephone_receiver:");%>
<%String pager = EmojiParser.parseToUnicode(":pager:");%>
<%String fax = EmojiParser.parseToUnicode(":fax:");%>
<%String minidisc = EmojiParser.parseToUnicode(":minidisc:");%>
<%String vhs = EmojiParser.parseToUnicode(":vhs:");%>
<%String sound = EmojiParser.parseToUnicode(":sound:");%>
<%String speaker = EmojiParser.parseToUnicode(":speaker:");%>
<%String mute = EmojiParser.parseToUnicode(":mute:");%>
<%String loudspeaker = EmojiParser.parseToUnicode(":loudspeaker:");%>
<%String mega = EmojiParser.parseToUnicode(":mega:");%>
<%String hourglass = EmojiParser.parseToUnicode(":hourglass:");%>
<%String hourglass_flowing_sand = EmojiParser.parseToUnicode(":hourglass_flowing_sand:");%>
<%String alarm_clock = EmojiParser.parseToUnicode(":alarm_clock:");%>
<%String watch = EmojiParser.parseToUnicode(":watch:");%>
<%String radio = EmojiParser.parseToUnicode(":radio:");%>
<%String satellite = EmojiParser.parseToUnicode(":satellite:");%>
<%String loop = EmojiParser.parseToUnicode(":loop:");%>
<%String mag = EmojiParser.parseToUnicode(":mag:");%>
<%String mag_right = EmojiParser.parseToUnicode(":mag_right:");%>
<%String unlock = EmojiParser.parseToUnicode(":unlock:");%>
<%String lock = EmojiParser.parseToUnicode(":lock:");%>
<%String lock_with_ink_pen = EmojiParser.parseToUnicode(":lock_with_ink_pen:");%>
<%String closed_lock_with_key = EmojiParser.parseToUnicode(":closed_lock_with_key:");%>
<%String key = EmojiParser.parseToUnicode(":key:");%>
<%String bulb = EmojiParser.parseToUnicode(":bulb:");%>
<%String flashlight = EmojiParser.parseToUnicode(":flashlight:");%>
<%String high_brightness = EmojiParser.parseToUnicode(":high_brightness:");%>
<%String low_brightness = EmojiParser.parseToUnicode(":low_brightness:");%>
<%String electric_plug = EmojiParser.parseToUnicode(":electric_plug:");%>
<%String battery = EmojiParser.parseToUnicode(":battery:");%>
<%String calling = EmojiParser.parseToUnicode(":calling:");%>
<%String email = EmojiParser.parseToUnicode(":email:");%>
<%String mailbox = EmojiParser.parseToUnicode(":mailbox:");%>
<%String postbox = EmojiParser.parseToUnicode(":postbox:");%>
<%String bath = EmojiParser.parseToUnicode(":bath:");%>
<%String bathtub = EmojiParser.parseToUnicode(":bathtub:");%>
<%String shower = EmojiParser.parseToUnicode(":shower:");%>
<%String toilet = EmojiParser.parseToUnicode(":toilet:");%>
<%String wrench = EmojiParser.parseToUnicode(":wrench:");%>
<%String nut_and_bolt = EmojiParser.parseToUnicode(":nut_and_bolt:");%>
<%String hammer = EmojiParser.parseToUnicode(":hammer:");%>
<%String seat = EmojiParser.parseToUnicode(":seat:");%>
<%String moneybag = EmojiParser.parseToUnicode(":moneybag:");%>
<%String yen = EmojiParser.parseToUnicode(":yen:");%>
<%String dollar = EmojiParser.parseToUnicode(":dollar:");%>
<%String pound = EmojiParser.parseToUnicode(":pound:");%>
<%String euro = EmojiParser.parseToUnicode(":euro:");%>
<%String credit_card = EmojiParser.parseToUnicode(":credit_card:");%>
<%String money_with_wings = EmojiParser.parseToUnicode(":money_with_wings:");%>
<%String inbox_tray = EmojiParser.parseToUnicode(":inbox_tray:");%>
<%String outbox_tray = EmojiParser.parseToUnicode(":outbox_tray:");%>
<%String envelope = EmojiParser.parseToUnicode(":envelope:");%>
<%String incoming_envelope = EmojiParser.parseToUnicode(":incoming_envelope:");%>
<%String postal_horn = EmojiParser.parseToUnicode(":postal_horn:");%>
<%String mailbox_closed = EmojiParser.parseToUnicode(":mailbox_closed:");%>
<%String mailbox_with_mail = EmojiParser.parseToUnicode(":mailbox_with_mail:");%>
<%String mailbox_with_no_mail = EmojiParser.parseToUnicode(":mailbox_with_no_mail:");%>
<%String door = EmojiParser.parseToUnicode(":door:");%>
<%String smoking = EmojiParser.parseToUnicode(":smoking:");%>
<%String bomb = EmojiParser.parseToUnicode(":bomb:");%>
<%String gun = EmojiParser.parseToUnicode(":gun:");%>
<%String hocho = EmojiParser.parseToUnicode(":hocho:");%>
<%String pill = EmojiParser.parseToUnicode(":pill:");%>
<%String syringe = EmojiParser.parseToUnicode(":syringe:");%>
<%String page_facing_up = EmojiParser.parseToUnicode(":page_facing_up:");%>
<%String page_with_curl = EmojiParser.parseToUnicode(":page_with_curl:");%>
<%String bookmark_tabs = EmojiParser.parseToUnicode(":bookmark_tabs:");%>
<%String bar_chart = EmojiParser.parseToUnicode(":bar_chart:");%>
<%String chart_with_upwards_trend = EmojiParser.parseToUnicode(":chart_with_upwards_trend:");%>
<%String chart_with_downwards_trend = EmojiParser.parseToUnicode(":chart_with_downwards_trend:");%>
<%String scroll = EmojiParser.parseToUnicode(":scroll:");%>
<%String clipboard = EmojiParser.parseToUnicode(":clipboard:");%>
<%String calendar = EmojiParser.parseToUnicode(":calendar:");%>
<%String date = EmojiParser.parseToUnicode(":date:");%>
<%String card_index = EmojiParser.parseToUnicode(":card_index:");%>
<%String file_folder = EmojiParser.parseToUnicode(":file_folder:");%>
<%String open_file_folder = EmojiParser.parseToUnicode(":open_file_folder:");%>
<%String scissors = EmojiParser.parseToUnicode(":scissors:");%>
<%String pushpin = EmojiParser.parseToUnicode(":pushpin:");%>
<%String paperclip = EmojiParser.parseToUnicode(":paperclip:");%>
<%String black_nib = EmojiParser.parseToUnicode(":black_nib:");%>
<%String pencil2 = EmojiParser.parseToUnicode(":pencil2:");%>
<%String straight_ruler = EmojiParser.parseToUnicode(":straight_ruler:");%>
<%String triangular_ruler = EmojiParser.parseToUnicode(":triangular_ruler:");%>
<%String closed_book = EmojiParser.parseToUnicode(":closed_book:");%>
<%String green_book = EmojiParser.parseToUnicode(":green_book:");%>
<%String blue_book = EmojiParser.parseToUnicode(":blue_book:");%>
<%String orange_book = EmojiParser.parseToUnicode(":orange_book:");%>
<%String notebook = EmojiParser.parseToUnicode(":notebook:");%>
<%String notebook_with_decorative_cover = EmojiParser.parseToUnicode(":notebook_with_decorative_cover:");%>
<%String ledger = EmojiParser.parseToUnicode(":ledger:");%>
<%String books = EmojiParser.parseToUnicode(":books:");%>
<%String bookmark = EmojiParser.parseToUnicode(":bookmark:");%>
<%String name_badge = EmojiParser.parseToUnicode(":name_badge:");%>
<%String microscope = EmojiParser.parseToUnicode(":microscope:");%>
<%String telescope = EmojiParser.parseToUnicode(":telescope:");%>
<%String newspaper = EmojiParser.parseToUnicode(":newspaper:");%>
<%String football = EmojiParser.parseToUnicode(":football:");%>
<%String basketball = EmojiParser.parseToUnicode(":basketball:");%>
<%String soccer = EmojiParser.parseToUnicode(":soccer:");%>
<%String baseball = EmojiParser.parseToUnicode(":baseball:");%>
<%String tennis = EmojiParser.parseToUnicode(":tennis:");%>
<%String rugby_football = EmojiParser.parseToUnicode(":rugby_football:");%>
<%String bowling = EmojiParser.parseToUnicode(":bowling:");%>
<%String golf = EmojiParser.parseToUnicode(":golf:");%>
<%String mountain_bicyclist = EmojiParser.parseToUnicode(":mountain_bicyclist:");%>
<%String bicyclist = EmojiParser.parseToUnicode(":bicyclist:");%>
<%String horse_racing = EmojiParser.parseToUnicode(":horse_racing:");%>
<%String snowboarder = EmojiParser.parseToUnicode(":snowboarder:");%>
<%String swimmer = EmojiParser.parseToUnicode(":swimmer:");%>
<%String surfer = EmojiParser.parseToUnicode(":surfer:");%>
<%String ski = EmojiParser.parseToUnicode(":ski:");%>
<%String spades = EmojiParser.parseToUnicode(":spades:");%>
<%String hearts = EmojiParser.parseToUnicode(":hearts:");%>
<%String clubs = EmojiParser.parseToUnicode(":clubs:");%>
<%String diamonds = EmojiParser.parseToUnicode(":diamonds:");%>
<%String gem = EmojiParser.parseToUnicode(":gem:");%>
<%String ring = EmojiParser.parseToUnicode(":ring:");%>
<%String trophy = EmojiParser.parseToUnicode(":trophy:");%>
<%String musical_score = EmojiParser.parseToUnicode(":musical_score:");%>
<%String musical_keyboard = EmojiParser.parseToUnicode(":musical_keyboard:");%>
<%String violin = EmojiParser.parseToUnicode(":violin:");%>
<%String space_invader = EmojiParser.parseToUnicode(":space_invader:");%>
<%String video_game = EmojiParser.parseToUnicode(":video_game:");%>
<%String black_joker = EmojiParser.parseToUnicode(":black_joker:");%>
<%String flower_playing_cards = EmojiParser.parseToUnicode(":flower_playing_cards:");%>
<%String game_die = EmojiParser.parseToUnicode(":game_die:");%>
<%String dart = EmojiParser.parseToUnicode(":dart:");%>
<%String mahjong = EmojiParser.parseToUnicode(":mahjong:");%>
<%String clapper = EmojiParser.parseToUnicode(":clapper:");%>
<%String memo = EmojiParser.parseToUnicode(":memo:");%>
<%String pencil = EmojiParser.parseToUnicode(":pencil:");%>
<%String book = EmojiParser.parseToUnicode(":book:");%>
<%String art = EmojiParser.parseToUnicode(":art:");%>
<%String microphone = EmojiParser.parseToUnicode(":microphone:");%>
<%String headphones = EmojiParser.parseToUnicode(":headphones:");%>
<%String trumpet = EmojiParser.parseToUnicode(":trumpet:");%>
<%String saxophone = EmojiParser.parseToUnicode(":saxophone:");%>
<%String guitar = EmojiParser.parseToUnicode(":guitar:");%>
<%String shoe = EmojiParser.parseToUnicode(":shoe:");%>
<%String sandal = EmojiParser.parseToUnicode(":sandal:");%>
<%String high_heel = EmojiParser.parseToUnicode(":high_heel:");%>
<%String lipstick = EmojiParser.parseToUnicode(":lipstick:");%>
<%String boot = EmojiParser.parseToUnicode(":boot:");%>
<%String shirt = EmojiParser.parseToUnicode(":shirt:");%>





  <div style="border:1px solid black;height:400px;width:1500px;overflow-x:scroll;">
    <p align="center" margin = "auto"><u>Emojis</u></p>
    <ul>
<li>:open_mouth:  <%= open_mouth%></li>
<li>:grimacing:  <%= grimacing%></li>
<li>:confused:  <%= confused%></li>
<li>:hushed:  <%= hushed%></li>
<li>:expressionless:  <%= expressionless%></li>
<li>:unamused:  <%= unamused%></li>
<li>:sweat_smile:  <%= sweat_smile%></li>
<li>:sweat:  <%= sweat%></li>
<li>:disappointed_relieved:  <%= disappointed_relieved%></li>
<li>:weary:  <%= weary%></li>
<li>:pensive:  <%= pensive%></li>
<li>:disappointed:  <%= disappointed%></li>
<li>:confounded:  <%= confounded%></li>
<li>:fearful:  <%= fearful%></li>
<li>:cold_sweat:  <%= cold_sweat%></li>
<li>:persevere:  <%= persevere%></li>
<li>:cry:  <%= cry%></li>
<li>:sob:  <%= sob%></li>
<li>:joy:  <%= joy%></li>
<li>:astonished:  <%= astonished%></li>
<li>:scream:  <%= scream%></li>
<li>:neckbeard:  <%= neckbeard%></li>
<li>:tired_face:  <%= tired_face%></li>
<li>:angry:  <%= angry%></li>
<li>:rage:  <%= rage%></li>
<li>:triumph:  <%= triumph%></li>
<li>:sleepy:  <%= sleepy%></li>
<li>:yum:  <%= yum%></li>
<li>:mask:  <%= mask%></li>
<li>:sunglasses:  <%= sunglasses%></li>
<li>:dizzy_face:  <%= dizzy_face%></li>
<li>:imp:  <%= imp%></li>
<li>:smiling_imp:  <%= smiling_imp%></li>
<li>:neutral_face:  <%= neutral_face%></li>
<li>:no_mouth:  <%= no_mouth%></li>
<li>:innocent:  <%= innocent%></li>
<li>:alien:  <%= alien%></li>
<li>:yellow_heart:  <%= yellow_heart%></li>
<li>:blue_heart:  <%= blue_heart%></li>
<li>:purple_heart:  <%= purple_heart%></li>
<li>:heart:  <%= heart%></li>
<li>:green_heart:  <%= green_heart%></li>
<li>:broken_heart:  <%= broken_heart%></li>
<li>:heartbeat:  <%= heartbeat%></li>
<li>:heartpulse:  <%= heartpulse%></li>
<li>:two_hearts:  <%= two_hearts%></li>
<li>:revolving_hearts:  <%= revolving_hearts%></li>
<li>:cupid:  <%= cupid%></li>
<li>:sparkling_heart:  <%= sparkling_heart%></li>
<li>:sparkles:  <%= sparkles%></li>
<li>:star:  <%= star%></li>
<li>:star2:  <%= star2%></li>
<li>:dizzy:  <%= dizzy%></li>
<li>:boom:  <%= boom%></li>
<li>:collision:  <%= collision%></li>
<li>:anger:  <%= anger%></li>
<li>:exclamation:  <%= exclamation%></li>
<li>:question:  <%= question%></li>
<li>:grey_exclamation:  <%= grey_exclamation%></li>
<li>:grey_question:  <%= grey_question%></li>
<li>:zzz:  <%= zzz%></li>
<li>:dash:  <%= dash%></li>
<li>:sweat_drops:  <%= sweat_drops%></li>
<li>:notes:  <%= notes%></li>
<li>:musical_note:  <%= musical_note%></li>
<li>:fire:  <%= fire%></li>
<li>:hankey:  <%= hankey%></li>
<li>:poop:  <%= poop%></li>
<li>:shit:  <%= shit%></li>
<li>:+1:  <%= +1%></li>
<li>:thumbsup:  <%= thumbsup%></li>
<li>:-1:  <%= -1%></li>
<li>:thumbsdown:  <%= thumbsdown%></li>
<li>:ok_hand:  <%= ok_hand%></li>
<li>:punch:  <%= punch%></li>
<li>:facepunch:  <%= facepunch%></li>
<li>:fist:  <%= fist%></li>
<li>:v:  <%= v%></li>
<li>:wave:  <%= wave%></li>
<li>:hand:  <%= hand%></li>
<li>:raised_hand:  <%= raised_hand%></li>
<li>:open_hands:  <%= open_hands%></li>
<li>:point_up:  <%= point_up%></li>
<li>:point_down:  <%= point_down%></li>
<li>:point_left:  <%= point_left%></li>
<li>:point_right:  <%= point_right%></li>
<li>:raised_hands:  <%= raised_hands%></li>
<li>:pray:  <%= pray%></li>
<li>:point_up_2:  <%= point_up_2%></li>
<li>:clap:  <%= clap%></li>
<li>:muscle:  <%= muscle%></li>
<li>:metal:  <%= metal%></li>
<li>:fu:  <%= fu%></li>
<li>:runner:  <%= runner%></li>
<li>:running:  <%= running%></li>
<li>:couple:  <%= couple%></li>
<li>:family:  <%= family%></li>
<li>:two_men_holding_hands:  <%= two_men_holding_hands%></li>
<li>:two_women_holding_hands:  <%= two_women_holding_hands%></li>
<li>:dancer:  <%= dancer%></li>
<li>:dancers:  <%= dancers%></li>
<li>:ok_woman:  <%= ok_woman%></li>
<li>:no_good:  <%= no_good%></li>
<li>:information_desk_person:  <%= information_desk_person%></li>
<li>:raising_hand:  <%= raising_hand%></li>
<li>:bride_with_veil:  <%= bride_with_veil%></li>
<li>:person_with_pouting_face:  <%= person_with_pouting_face%></li>
<li>:person_frowning:  <%= person_frowning%></li>
<li>:bow:  <%= bow%></li>
<li>:couplekiss:  <%= couplekiss%></li>
<li>:couple_with_heart:  <%= couple_with_heart%></li>
<li>:massage:  <%= massage%></li>
<li>:haircut:  <%= haircut%></li>
<li>:nail_care:  <%= nail_care%></li>
<li>:boy:  <%= boy%></li>
<li>:girl:  <%= girl%></li>
<li>:woman:  <%= woman%></li>
<li>:man:  <%= man%></li>
<li>:baby:  <%= baby%></li>
<li>:older_woman:  <%= older_woman%></li>
<li>:older_man:  <%= older_man%></li>
<li>:person_with_blond_hair:  <%= person_with_blond_hair%></li>
<li>:man_with_gua_pi_mao:  <%= man_with_gua_pi_mao%></li>
<li>:man_with_turban:  <%= man_with_turban%></li>
<li>:construction_worker:  <%= construction_worker%></li>
<li>:cop:  <%= cop%></li>
<li>:angel:  <%= angel%></li>
<li>:princess:  <%= princess%></li>
<li>:smiley_cat:  <%= smiley_cat%></li>
<li>:smile_cat:  <%= smile_cat%></li>
<li>:heart_eyes_cat:  <%= heart_eyes_cat%></li>
<li>:kissing_cat:  <%= kissing_cat%></li>
<li>:smirk_cat:  <%= smirk_cat%></li>
<li>:scream_cat:  <%= scream_cat%></li>
<li>:crying_cat_face:  <%= crying_cat_face%></li>
<li>:joy_cat:  <%= joy_cat%></li>
<li>:pouting_cat:  <%= pouting_cat%></li>
<li>:japanese_ogre:  <%= japanese_ogre%></li>
<li>:japanese_goblin:  <%= japanese_goblin%></li>
<li>:see_no_evil:  <%= see_no_evil%></li>
<li>:hear_no_evil:  <%= hear_no_evil%></li>
<li>:speak_no_evil:  <%= speak_no_evil%></li>
<li>:guardsman:  <%= guardsman%></li>
<li>:skull:  <%= skull%></li>
<li>:feet:  <%= feet%></li>
<li>:lips:  <%= lips%></li>
<li>:kiss:  <%= kiss%></li>
<li>:droplet:  <%= droplet%></li>
<li>:ear:  <%= ear%></li>
<li>:eyes:  <%= eyes%></li>
<li>:nose:  <%= nose%></li>
<li>:tongue:  <%= tongue%></li>
<li>:love_letter:  <%= love_letter%></li>
<li>:bust_in_silhouette:  <%= bust_in_silhouette%></li>
<li>:busts_in_silhouette:  <%= busts_in_silhouette%></li>
<li>:speech_balloon:  <%= speech_balloon%></li>
<li>:thought_balloon:  <%= thought_balloon%></li>
<li>:feelsgood:  <%= feelsgood%></li>
<li>:finnadie:  <%= finnadie%></li>
<li>:goberserk:  <%= goberserk%></li>
<li>:godmode:  <%= godmode%></li>
<li>:hurtrealbad:  <%= hurtrealbad%></li>
<li>:rage1:  <%= rage1%></li>
<li>:rage2:  <%= rage2%></li>
<li>:rage3:  <%= rage3%></li>
<li>:rage4:  <%= rage4%></li>
<li>:suspect:  <%= suspect%></li>
<li>:trollface:  <%= trollface%></li>
<li>:sunny:  <%= sunny%></li>
<li>:umbrella:  <%= umbrella%></li>
<li>:cloud:  <%= cloud%></li>
<li>:snowflake:  <%= snowflake%></li>
<li>:snowman:  <%= snowman%></li>
<li>:zap:  <%= zap%></li>
<li>:cyclone:  <%= cyclone%></li>
<li>:foggy:  <%= foggy%></li>
<li>:ocean:  <%= ocean%></li>
<li>:cat:  <%= cat%></li>
<li>:dog:  <%= dog%></li>
<li>:mouse:  <%= mouse%></li>
<li>:hamster:  <%= hamster%></li>
<li>:rabbit:  <%= rabbit%></li>
<li>:wolf:  <%= wolf%></li>
<li>:frog:  <%= frog%></li>
<li>:tiger:  <%= tiger%></li>
<li>:koala:  <%= koala%></li>
<li>:bear:  <%= bear%></li>
<li>:pig:  <%= pig%></li>
<li>:pig_nose:  <%= pig_nose%></li>
<li>:cow:  <%= cow%></li>
<li>:boar:  <%= boar%></li>
<li>:monkey_face:  <%= monkey_face%></li>
<li>:monkey:  <%= monkey%></li>
<li>:horse:  <%= horse%></li>
<li>:racehorse:  <%= racehorse%></li>
<li>:camel:  <%= camel%></li>
<li>:sheep:  <%= sheep%></li>
<li>:elephant:  <%= elephant%></li>
<li>:panda_face:  <%= panda_face%></li>
<li>:snake:  <%= snake%></li>
<li>:bird:  <%= bird%></li>
<li>:baby_chick:  <%= baby_chick%></li>
<li>:hatched_chick:  <%= hatched_chick%></li>
<li>:hatching_chick:  <%= hatching_chick%></li>
<li>:chicken:  <%= chicken%></li>
<li>:penguin:  <%= penguin%></li>
<li>:turtle:  <%= turtle%></li>
<li>:bug:  <%= bug%></li>
<li>:honeybee:  <%= honeybee%></li>
<li>:ant:  <%= ant%></li>
<li>:beetle:  <%= beetle%></li>
<li>:snail:  <%= snail%></li>
<li>:octopus:  <%= octopus%></li>
<li>:tropical_fish:  <%= tropical_fish%></li>
<li>:fish:  <%= fish%></li>
<li>:whale:  <%= whale%></li>
<li>:whale2:  <%= whale2%></li>
<li>:dolphin:  <%= dolphin%></li>
<li>:cow2:  <%= cow2%></li>
<li>:ram:  <%= ram%></li>
<li>:rat:  <%= rat%></li>
<li>:water_buffalo:  <%= water_buffalo%></li>
<li>:tiger2:  <%= tiger2%></li>
<li>:rabbit2:  <%= rabbit2%></li>
<li>:dragon:  <%= dragon%></li>
<li>:goat:  <%= goat%></li>
<li>:rooster:  <%= rooster%></li>
<li>:dog2:  <%= dog2%></li>
<li>:pig2:  <%= pig2%></li>
<li>:mouse2:  <%= mouse2%></li>
<li>:ox:  <%= ox%></li>
<li>:dragon_face:  <%= dragon_face%></li>
<li>:blowfish:  <%= blowfish%></li>
<li>:crocodile:  <%= crocodile%></li>
<li>:dromedary_camel:  <%= dromedary_camel%></li>
<li>:leopard:  <%= leopard%></li>
<li>:cat2:  <%= cat2%></li>
<li>:poodle:  <%= poodle%></li>
<li>:paw_prints:  <%= paw_prints%></li>
<li>:bouquet:  <%= bouquet%></li>
<li>:cherry_blossom:  <%= cherry_blossom%></li>
<li>:tulip:  <%= tulip%></li>
<li>:four_leaf_clover:  <%= four_leaf_clover%></li>
<li>:rose:  <%= rose%></li>
<li>:sunflower:  <%= sunflower%></li>
<li>:hibiscus:  <%= hibiscus%></li>
<li>:maple_leaf:  <%= maple_leaf%></li>
<li>:leaves:  <%= leaves%></li>
<li>:fallen_leaf:  <%= fallen_leaf%></li>
<li>:herb:  <%= herb%></li>
<li>:mushroom:  <%= mushroom%></li>
<li>:cactus:  <%= cactus%></li>
<li>:palm_tree:  <%= palm_tree%></li>
<li>:evergreen_tree:  <%= evergreen_tree%></li>
<li>:deciduous_tree:  <%= deciduous_tree%></li>
<li>:chestnut:  <%= chestnut%></li>
<li>:seedling:  <%= seedling%></li>
<li>:blossom:  <%= blossom%></li>
<li>:ear_of_rice:  <%= ear_of_rice%></li>
<li>:shell:  <%= shell%></li>
<li>:globe_with_meridians:  <%= globe_with_meridians%></li>
<li>:sun_with_face:  <%= sun_with_face%></li>
<li>:full_moon_with_face:  <%= full_moon_with_face%></li>
<li>:new_moon_with_face:  <%= new_moon_with_face%></li>
<li>:new_moon:  <%= new_moon%></li>
<li>:waxing_crescent_moon:  <%= waxing_crescent_moon%></li>
<li>:first_quarter_moon:  <%= first_quarter_moon%></li>
<li>:waxing_gibbous_moon:  <%= waxing_gibbous_moon%></li>
<li>:full_moon:  <%= full_moon%></li>
<li>:waning_gibbous_moon:  <%= waning_gibbous_moon%></li>
<li>:last_quarter_moon:  <%= last_quarter_moon%></li>
<li>:waning_crescent_moon:  <%= waning_crescent_moon%></li>
<li>:last_quarter_moon_with_face:  <%= last_quarter_moon_with_face%></li>
<li>:first_quarter_moon_with_face:  <%= first_quarter_moon_with_face%></li>
<li>:crescent_moon:  <%= crescent_moon%></li>
<li>:earth_africa:  <%= earth_africa%></li>
<li>:earth_americas:  <%= earth_americas%></li>
<li>:earth_asia:  <%= earth_asia%></li>
<li>:volcano:  <%= volcano%></li>
<li>:milky_way:  <%= milky_way%></li>
<li>:partly_sunny:  <%= partly_sunny%></li>
<li>:octocat:  <%= octocat%></li>
<li>:squirrel:  <%= squirrel%></li>
<li>:bamboo:  <%= bamboo%></li>
<li>:gift_heart:  <%= gift_heart%></li>
<li>:dolls:  <%= dolls%></li>
<li>:school_satchel:  <%= school_satchel%></li>
<li>:mortar_board:  <%= mortar_board%></li>
<li>:flags:  <%= flags%></li>
<li>:fireworks:  <%= fireworks%></li>
<li>:sparkler:  <%= sparkler%></li>
<li>:wind_chime:  <%= wind_chime%></li>
<li>:rice_scene:  <%= rice_scene%></li>
<li>:jack_o_lantern:  <%= jack_o_lantern%></li>
<li>:ghost:  <%= ghost%></li>
<li>:santa:  <%= santa%></li>
<li>:christmas_tree:  <%= christmas_tree%></li>
<li>:gift:  <%= gift%></li>
<li>:bell:  <%= bell%></li>
<li>:no_bell:  <%= no_bell%></li>
<li>:tanabata_tree:  <%= tanabata_tree%></li>
<li>:tada:  <%= tada%></li>
<li>:confetti_ball:  <%= confetti_ball%></li>
<li>:balloon:  <%= balloon%></li>
<li>:crystal_ball:  <%= crystal_ball%></li>
<li>:cd:  <%= cd%></li>
<li>:dvd:  <%= dvd%></li>
<li>:floppy_disk:  <%= floppy_disk%></li>
<li>:camera:  <%= camera%></li>
<li>:video_camera:  <%= video_camera%></li>
<li>:movie_camera:  <%= movie_camera%></li>
<li>:computer:  <%= computer%></li>
<li>:tv:  <%= tv%></li>
<li>:iphone:  <%= iphone%></li>
<li>:phone:  <%= phone%></li>
<li>:telephone:  <%= telephone%></li>
<li>:telephone_receiver:  <%= telephone_receiver%></li>
<li>:pager:  <%= pager%></li>
<li>:fax:  <%= fax%></li>
<li>:minidisc:  <%= minidisc%></li>
<li>:vhs:  <%= vhs%></li>
<li>:sound:  <%= sound%></li>
<li>:speaker:  <%= speaker%></li>
<li>:mute:  <%= mute%></li>
<li>:loudspeaker:  <%= loudspeaker%></li>
<li>:mega:  <%= mega%></li>
<li>:hourglass:  <%= hourglass%></li>
<li>:hourglass_flowing_sand:  <%= hourglass_flowing_sand%></li>
<li>:alarm_clock:  <%= alarm_clock%></li>
<li>:watch:  <%= watch%></li>
<li>:radio:  <%= radio%></li>
<li>:satellite:  <%= satellite%></li>
<li>:loop:  <%= loop%></li>
<li>:mag:  <%= mag%></li>
<li>:mag_right:  <%= mag_right%></li>
<li>:unlock:  <%= unlock%></li>
<li>:lock:  <%= lock%></li>
<li>:lock_with_ink_pen:  <%= lock_with_ink_pen%></li>
<li>:closed_lock_with_key:  <%= closed_lock_with_key%></li>
<li>:key:  <%= key%></li>
<li>:bulb:  <%= bulb%></li>
<li>:flashlight:  <%= flashlight%></li>
<li>:high_brightness:  <%= high_brightness%></li>
<li>:low_brightness:  <%= low_brightness%></li>
<li>:electric_plug:  <%= electric_plug%></li>
<li>:battery:  <%= battery%></li>
<li>:calling:  <%= calling%></li>
<li>:email:  <%= email%></li>
<li>:mailbox:  <%= mailbox%></li>
<li>:postbox:  <%= postbox%></li>
<li>:bath:  <%= bath%></li>
<li>:bathtub:  <%= bathtub%></li>
<li>:shower:  <%= shower%></li>
<li>:toilet:  <%= toilet%></li>
<li>:wrench:  <%= wrench%></li>
<li>:nut_and_bolt:  <%= nut_and_bolt%></li>
<li>:hammer:  <%= hammer%></li>
<li>:seat:  <%= seat%></li>
<li>:moneybag:  <%= moneybag%></li>
<li>:yen:  <%= yen%></li>
<li>:dollar:  <%= dollar%></li>
<li>:pound:  <%= pound%></li>
<li>:euro:  <%= euro%></li>
<li>:credit_card:  <%= credit_card%></li>
<li>:money_with_wings:  <%= money_with_wings%></li>
<li>:inbox_tray:  <%= inbox_tray%></li>
<li>:outbox_tray:  <%= outbox_tray%></li>
<li>:envelope:  <%= envelope%></li>
<li>:incoming_envelope:  <%= incoming_envelope%></li>
<li>:postal_horn:  <%= postal_horn%></li>
<li>:mailbox_closed:  <%= mailbox_closed%></li>
<li>:mailbox_with_mail:  <%= mailbox_with_mail%></li>
<li>:mailbox_with_no_mail:  <%= mailbox_with_no_mail%></li>
<li>:door:  <%= door%></li>
<li>:smoking:  <%= smoking%></li>
<li>:bomb:  <%= bomb%></li>
<li>:gun:  <%= gun%></li>
<li>:hocho:  <%= hocho%></li>
<li>:pill:  <%= pill%></li>
<li>:syringe:  <%= syringe%></li>
<li>:page_facing_up:  <%= page_facing_up%></li>
<li>:page_with_curl:  <%= page_with_curl%></li>
<li>:bookmark_tabs:  <%= bookmark_tabs%></li>
<li>:bar_chart:  <%= bar_chart%></li>
<li>:chart_with_upwards_trend:  <%= chart_with_upwards_trend%></li>
<li>:chart_with_downwards_trend:  <%= chart_with_downwards_trend%></li>
<li>:scroll:  <%= scroll%></li>
<li>:clipboard:  <%= clipboard%></li>
<li>:calendar:  <%= calendar%></li>
<li>:date:  <%= date%></li>
<li>:card_index:  <%= card_index%></li>
<li>:file_folder:  <%= file_folder%></li>
<li>:open_file_folder:  <%= open_file_folder%></li>
<li>:scissors:  <%= scissors%></li>
<li>:pushpin:  <%= pushpin%></li>
<li>:paperclip:  <%= paperclip%></li>
<li>:black_nib:  <%= black_nib%></li>
<li>:pencil2:  <%= pencil2%></li>
<li>:straight_ruler:  <%= straight_ruler%></li>
<li>:triangular_ruler:  <%= triangular_ruler%></li>
<li>:closed_book:  <%= closed_book%></li>
<li>:green_book:  <%= green_book%></li>
<li>:blue_book:  <%= blue_book%></li>
<li>:orange_book:  <%= orange_book%></li>
<li>:notebook:  <%= notebook%></li>
<li>:notebook_with_decorative_cover:  <%= notebook_with_decorative_cover%></li>
<li>:ledger:  <%= ledger%></li>
<li>:books:  <%= books%></li>
<li>:bookmark:  <%= bookmark%></li>
<li>:name_badge:  <%= name_badge%></li>
<li>:microscope:  <%= microscope%></li>
<li>:telescope:  <%= telescope%></li>
<li>:newspaper:  <%= newspaper%></li>
<li>:football:  <%= football%></li>
<li>:basketball:  <%= basketball%></li>
<li>:soccer:  <%= soccer%></li>
<li>:baseball:  <%= baseball%></li>
<li>:tennis:  <%= tennis%></li>
<li>:rugby_football:  <%= rugby_football%></li>
<li>:bowling:  <%= bowling%></li>
<li>:golf:  <%= golf%></li>
<li>:mountain_bicyclist:  <%= mountain_bicyclist%></li>
<li>:bicyclist:  <%= bicyclist%></li>
<li>:horse_racing:  <%= horse_racing%></li>
<li>:snowboarder:  <%= snowboarder%></li>
<li>:swimmer:  <%= swimmer%></li>
<li>:surfer:  <%= surfer%></li>
<li>:ski:  <%= ski%></li>
<li>:spades:  <%= spades%></li>
<li>:hearts:  <%= hearts%></li>
<li>:clubs:  <%= clubs%></li>
<li>:diamonds:  <%= diamonds%></li>
<li>:gem:  <%= gem%></li>
<li>:ring:  <%= ring%></li>
<li>:trophy:  <%= trophy%></li>
<li>:musical_score:  <%= musical_score%></li>
<li>:musical_keyboard:  <%= musical_keyboard%></li>
<li>:violin:  <%= violin%></li>
<li>:space_invader:  <%= space_invader%></li>
<li>:video_game:  <%= video_game%></li>
<li>:black_joker:  <%= black_joker%></li>
<li>:flower_playing_cards:  <%= flower_playing_cards%></li>
<li>:game_die:  <%= game_die%></li>
<li>:dart:  <%= dart%></li>
<li>:mahjong:  <%= mahjong%></li>
<li>:clapper:  <%= clapper%></li>
<li>:memo:  <%= memo%></li>
<li>:pencil:  <%= pencil%></li>
<li>:book:  <%= book%></li>
<li>:art:  <%= art%></li>
<li>:microphone:  <%= microphone%></li>
<li>:headphones:  <%= headphones%></li>
<li>:trumpet:  <%= trumpet%></li>
<li>:saxophone:  <%= saxophone%></li>
<li>:guitar:  <%= guitar%></li>
<li>:shoe:  <%= shoe%></li>
<li>:sandal:  <%= sandal%></li>
<li>:high_heel:  <%= high_heel%></li>
<li>:lipstick:  <%= lipstick%></li>
<li>:boot:  <%= boot%></li>
<li>:shirt:  <%= shirt%></li>

     
  <div>

</body>
</html>
